name: build

on: pull_request

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '15.14.0'
      - run: npm ci
        working-directory: codebase/rdicidr-0.1.0
      - run: npm run lint
        working-directory: codebase/rdicidr-0.1.0
      - run: npm run prettier
        working-directory: codebase/rdicidr-0.1.0
      - run: npm run test
        env:
          CI: true
        working-directory: codebase/rdicidr-0.1.0
      - run: npm run build
        working-directory: codebase/rdicidr-0.1.0